const MAINNET_SYNTHS = [
  {
    asset: 'USD',
    category: 'forex',
    sign: '$',
    description: 'US Dollars',
    name: 'sUSD',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0xb49f677943BC038e9857d61E7d053CaA2C1734C1',
    asset: 'EUR',
    category: 'forex',
    sign: '€',
    description: 'Euros',
    name: 'sEUR',
  },
  {
    feed: '0xBcE206caE7f0ec07b545EddE332A47C2F75bbeb3',
    asset: 'JPY',
    category: 'forex',
    sign: '¥',
    description: 'Japanese Yen',
    name: 'sJPY',
  },
  {
    feed: '0x77F9710E7d0A19669A13c055F62cd80d313dF022',
    asset: 'AUD',
    category: 'forex',
    sign: '$',
    description: 'Australian Dollars',
    name: 'sAUD',
  },
  {
    feed: '0x5c0Ab2d9b5a7ed9f470386e82BB36A3613cDd4b5',
    asset: 'GBP',
    category: 'forex',
    sign: '£',
    description: 'Pound Sterling',
    name: 'sGBP',
  },
  {
    feed: '0x449d117117838fFA61263B61dA6301AA2a88B13A',
    asset: 'CHF',
    category: 'forex',
    sign: 'Fr',
    description: 'Swiss Franc',
    name: 'sCHF',
  },
  {
    feed: '0x214eD9Da11D2fbe465a6fc601a91E62EbEc1a0D6',
    asset: 'XAU',
    category: 'commodity',
    sign: 'oz',
    description: 'Gold Ounce',
    name: 'sXAU',
  },
  {
    feed: '0x379589227b15F1a12195D3f2d90bBc9F31f95235',
    asset: 'XAG',
    category: 'commodity',
    sign: 'oz',
    description: 'Silver Ounce',
    name: 'sXAG',
  },
  {
    feed: '0xb70ba475F1a6b5396e46d9b2a5f7081080Dc9d09',
    asset: 'OIL',
    category: 'commodity',
    sign: '$',
    description: 'Brent Crude Oil',
    name: 'sOIL',
  },
  {
    feed: '0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Bitcoin',
    name: 'sBTC',
  },
  {
    feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Ether',
    name: 'sETH',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x14e613AC84a31f709eadbdF89C6CC390fDc9540A',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    description: 'Binance Coin',
    name: 'sBNB',
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0xacD0D1A29759CC01E8D925371B72cb2b5610EA25',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    description: 'TRON',
    name: 'sTRX',
  },
  {
    feed: '0x5239a625dEb44bF3EeAc2CD5366ba24b8e9DB63F',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    description: 'Tezos',
    name: 'sXTZ',
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0xCed2660c6Dd1Ffd856A5A82C67f3482d88C50b12',
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    description: 'Ripple',
    name: 'sXRP',
  },
  {
    feed: '0x6AF09DF7563C363B5763b9102712EbeD3b9e859B',
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    description: 'Litecoin',
    name: 'sLTC',
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x2c1d072e956AFFC0D435Cb7AC38EF18d24d9127c',
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    description: 'Chainlink',
    name: 'sLINK',
  },
  {
    feed: '0x10a43289895eAff840E8d45995BBa89f9115ECEe',
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    description: 'EOS',
    name: 'sEOS',
  },
  {
    asset: 'BCH',
    category: 'crypto',
    sign: '',
    description: 'Bitcoin Cash',
    name: 'sBCH',
  },
  {
    feed: '0xaEA2808407B7319A31A383B6F8B60f04BCa23cE2',
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    description: 'Ethereum Classic',
    name: 'sETC',
  },
  {
    feed: '0xFb0cADFEa136E9E343cfb55B863a6Df8348ab912',
    asset: 'DASH',
    category: 'crypto',
    sign: '',
    description: 'Dash',
    name: 'sDASH',
  },
  {
    feed: '0xFA66458Cce7Dd15D8650015c4fce4D278271618F',
    asset: 'XMR',
    category: 'crypto',
    sign: '',
    description: 'Monero',
    name: 'sXMR',
  },
  {
    feed: '0xAE48c91dF1fE419994FFDa27da09D5aC69c30f55',
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    description: 'Cardano',
    name: 'sADA',
  },
  {
    feed: '0xE23FA0e8dd05D6f66a6e8c98cab2d9AE82A7550c',
    asset: 'FTSE100',
    category: 'equities',
    sign: '',
    exchange: 'LSE',
    description: 'FTSE 100 Index',
    name: 'sFTSE',
  },
  {
    feed: '0x5c4939a2ab3A2a9f93A518d81d4f8D0Bc6a68980',
    asset: 'NIKKEI225',
    category: 'equities',
    sign: '',
    exchange: 'TSE',
    description: 'Nikkei 225 Index',
    name: 'sNIKKEI',
  },
  {
    feed: '0x283D433435cFCAbf00263beEF6A362b7cc5ed9f2',
    asset: 'CEX',
    category: 'index',
    sign: '',
    description: 'Centralised Exchange Index',
    name: 'sCEX',
    index: [
      {
        asset: 'BNB',
        category: 'crypto',
        sign: '',
        description: 'Binance Coin',
        units: 12.88,
        weight: 29.15,
      },
      {
        asset: 'CRO',
        category: 'crypto',
        sign: '',
        description: 'Crypto com',
        units: 1303.31,
        weight: 24.3,
      },
      {
        asset: 'LEO',
        category: 'crypto',
        sign: '',
        description: 'UNUS SED LEO',
        units: 94.54,
        weight: 13.42,
      },
      {
        asset: 'HT',
        category: 'crypto',
        sign: '',
        description: 'Huobi Token',
        units: 23.06,
        weight: 11.73,
      },
      {
        asset: 'FTT',
        category: 'crypto',
        sign: '',
        description: 'FTX',
        units: 9.36,
        weight: 3.56,
      },
      {
        asset: 'OKB',
        category: 'crypto',
        sign: '',
        description: 'OKB',
        units: 25.72,
        weight: 16.97,
      },
      {
        asset: 'KCS',
        category: 'crypto',
        sign: '',
        description: 'KuCoin Shares',
        units: 9.18,
        weight: 0.87,
      },
    ],
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0xa8E875F94138B0C5b51d1e1d5dE35bbDdd28EA87',
    asset: 'DEFI',
    category: 'index',
    sign: '',
    description: 'DeFi Index',
    name: 'sDEFI',
    index: [
      {
        asset: 'COMP',
        category: 'crypto',
        sign: '',
        description: 'Compound',
        units: 1.88,
        weight: 7.5,
      },
      {
        asset: 'MKR',
        category: 'crypto',
        sign: '',
        description: 'Maker',
        units: 0.39,
        weight: 7.5,
      },
      {
        asset: 'AAVE',
        category: 'crypto',
        sign: '',
        description: 'Aave',
        units: 8.41,
        weight: 15,
      },
      {
        asset: 'UMA',
        category: 'crypto',
        sign: '',
        description: 'UMA',
        units: 19.47,
        weight: 5,
      },
      {
        asset: 'SNX',
        category: 'crypto',
        sign: '',
        description: 'Synthetix Network Token',
        units: 109.93,
        weight: 15,
      },
      {
        asset: 'REN',
        category: 'crypto',
        sign: '',
        description: 'Ren',
        units: 598.03,
        weight: 5,
      },
      {
        asset: 'UNI',
        category: 'crypto',
        sign: '',
        description: 'Uniswap',
        units: 92.09,
        weight: 10,
      },
      {
        asset: 'KNC',
        category: 'crypto',
        sign: '',
        description: 'Kyber Network',
        units: 159.13,
        weight: 5,
      },
      {
        asset: 'CRV',
        category: 'crypto',
        sign: '',
        description: 'Curve DAO Token',
        units: 253.8,
        weight: 5,
      },
      {
        asset: 'WNXM',
        category: 'crypto',
        sign: '',
        description: 'Wrapped Nexus Mutual',
        units: 4.53,
        weight: 5,
      },
      {
        asset: 'YFI',
        category: 'crypto',
        sign: '',
        description: 'yearn.finance',
        units: 0.023,
        weight: 15,
      },
      {
        asset: 'BAL',
        category: 'crypto',
        sign: '',
        description: 'Balancer',
        units: 9.05,
        weight: 5,
      },
    ],
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Inverse Bitcoin',
    name: 'iBTC',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 15699, upperLimit: 27473.25, lowerLimit: 3924.75 },
  },
  {
    feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Inverse Ether',
    name: 'iETH',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 578.01, upperLimit: 867.02, lowerLimit: 289.01 },
  },
  {
    feed: '0x14e613AC84a31f709eadbdF89C6CC390fDc9540A',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    description: 'Inverse Binance Coin',
    name: 'iBNB',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 22.88, upperLimit: 34.32, lowerLimit: 11.44 },
  },
  {
    feed: '0xacD0D1A29759CC01E8D925371B72cb2b5610EA25',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    description: 'Inverse TRON',
    name: 'iTRX',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 0.0267, upperLimit: 0.04, lowerLimit: 0.0133 },
  },
  {
    feed: '0x5239a625dEb44bF3EeAc2CD5366ba24b8e9DB63F',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    description: 'Inverse Tezos',
    name: 'iXTZ',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 2.542, upperLimit: 3.813, lowerLimit: 1.271 },
  },
  {
    feed: '0xCed2660c6Dd1Ffd856A5A82C67f3482d88C50b12',
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    description: 'Inverse Ripple',
    name: 'iXRP',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 0.1883, upperLimit: 0.282, lowerLimit: 0.094 },
  },
  {
    feed: '0x2c1d072e956AFFC0D435Cb7AC38EF18d24d9127c',
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    description: 'Inverse Chainlink',
    name: 'iLINK',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 12.73, upperLimit: 19.095, lowerLimit: 6.365 },
  },
  {
    feed: '0x6AF09DF7563C363B5763b9102712EbeD3b9e859B',
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    description: 'Inverse Litecoin',
    name: 'iLTC',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 48.12, upperLimit: 72.18, lowerLimit: 24.06 },
  },
  {
    feed: '0x10a43289895eAff840E8d45995BBa89f9115ECEe',
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    description: 'Inverse EOS',
    name: 'iEOS',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 2.22, upperLimit: 3.33, lowerLimit: 1.11 },
  },
  {
    asset: 'BCH',
    category: 'crypto',
    sign: '',
    description: 'Inverse Bitcoin Cash',
    name: 'iBCH',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 229.54, upperLimit: 344.31, lowerLimit: 114.77 },
  },
  {
    feed: '0xaEA2808407B7319A31A383B6F8B60f04BCa23cE2',
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    description: 'Inverse Ethereum Classic',
    name: 'iETC',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 6.16, upperLimit: 9.24, lowerLimit: 3.08 },
  },
  {
    feed: '0xFb0cADFEa136E9E343cfb55B863a6Df8348ab912',
    asset: 'DASH',
    category: 'crypto',
    sign: '',
    description: 'Inverse Dash',
    name: 'iDASH',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 64.44, upperLimit: 96.66, lowerLimit: 32.22 },
  },
  {
    feed: '0xFA66458Cce7Dd15D8650015c4fce4D278271618F',
    asset: 'XMR',
    category: 'crypto',
    sign: '',
    description: 'Inverse Monero',
    name: 'iXMR',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 132.26, upperLimit: 198.4, lowerLimit: 66.13 },
  },
  {
    feed: '0xAE48c91dF1fE419994FFDa27da09D5aC69c30f55',
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    description: 'Inverse Cardano',
    name: 'iADA',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 0.133, upperLimit: 0.1995, lowerLimit: 0.0665 },
  },
  {
    feed: '0x283D433435cFCAbf00263beEF6A362b7cc5ed9f2',
    asset: 'CEX',
    category: 'index',
    sign: '',
    description: 'Inverse Centralised Exchange Index',
    name: 'iCEX',
    index: [
      {
        asset: 'BNB',
        category: 'crypto',
        sign: '',
        description: 'Binance Coin',
        units: 12.88,
        weight: 29.15,
      },
      {
        asset: 'CRO',
        category: 'crypto',
        sign: '',
        description: 'Crypto com',
        units: 1303.31,
        weight: 24.3,
      },
      {
        asset: 'LEO',
        category: 'crypto',
        sign: '',
        description: 'UNUS SED LEO',
        units: 94.54,
        weight: 13.42,
      },
      {
        asset: 'HT',
        category: 'crypto',
        sign: '',
        description: 'Huobi Token',
        units: 23.06,
        weight: 11.73,
      },
      {
        asset: 'FTT',
        category: 'crypto',
        sign: '',
        description: 'FTX',
        units: 9.36,
        weight: 3.56,
      },
      {
        asset: 'OKB',
        category: 'crypto',
        sign: '',
        description: 'OKB',
        units: 25.72,
        weight: 16.97,
      },
      {
        asset: 'KCS',
        category: 'crypto',
        sign: '',
        description: 'KuCoin Shares',
        units: 9.18,
        weight: 0.87,
      },
    ],
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 988.56, upperLimit: 1482.84, lowerLimit: 494.28 },
  },
  {
    feed: '0xa8E875F94138B0C5b51d1e1d5dE35bbDdd28EA87',
    asset: 'DEFI',
    category: 'index',
    sign: '',
    description: 'Inverse DeFi Index',
    name: 'iDEFI',
    index: [
      {
        asset: 'COMP',
        category: 'crypto',
        sign: '',
        description: 'Compound',
        units: 1.88,
        weight: 7.5,
      },
      {
        asset: 'MKR',
        category: 'crypto',
        sign: '',
        description: 'Maker',
        units: 0.39,
        weight: 7.5,
      },
      {
        asset: 'AAVE',
        category: 'crypto',
        sign: '',
        description: 'Aave',
        units: 8.41,
        weight: 15,
      },
      {
        asset: 'UMA',
        category: 'crypto',
        sign: '',
        description: 'UMA',
        units: 19.47,
        weight: 5,
      },
      {
        asset: 'SNX',
        category: 'crypto',
        sign: '',
        description: 'Synthetix Network Token',
        units: 109.93,
        weight: 15,
      },
      {
        asset: 'REN',
        category: 'crypto',
        sign: '',
        description: 'Ren',
        units: 598.03,
        weight: 5,
      },
      {
        asset: 'UNI',
        category: 'crypto',
        sign: '',
        description: 'Uniswap',
        units: 92.09,
        weight: 10,
      },
      {
        asset: 'KNC',
        category: 'crypto',
        sign: '',
        description: 'Kyber Network',
        units: 159.13,
        weight: 5,
      },
      {
        asset: 'CRV',
        category: 'crypto',
        sign: '',
        description: 'Curve DAO Token',
        units: 253.8,
        weight: 5,
      },
      {
        asset: 'WNXM',
        category: 'crypto',
        sign: '',
        description: 'Wrapped Nexus Mutual',
        units: 4.53,
        weight: 5,
      },
      {
        asset: 'YFI',
        category: 'crypto',
        sign: '',
        description: 'yearn.finance',
        units: 0.023,
        weight: 15,
      },
      {
        asset: 'BAL',
        category: 'crypto',
        sign: '',
        description: 'Balancer',
        units: 9.05,
        weight: 5,
      },
    ],
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 2714.42, upperLimit: 4071.63, lowerLimit: 1357.21 },
  },
  {
    feed: '0xb70ba475F1a6b5396e46d9b2a5f7081080Dc9d09',
    asset: 'OIL',
    category: 'commodity',
    sign: '$',
    description: 'Inverse Brent Crude Oil',
    name: 'iOIL',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 44.9459, upperLimit: 67.4189, lowerLimit: 22.473 },
  },
];

const TESTNET_SYNTHS = [
  {
    asset: 'USD',
    category: 'forex',
    sign: '$',
    description: 'US Dollars',
    name: 'sUSD',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x0',
    asset: 'EUR',
    category: 'forex',
    sign: '€',
    description: 'Euros',
    name: 'sEUR',
  },
  {
    feed: '0x0',
    asset: 'JPY',
    category: 'forex',
    sign: '¥',
    description: 'Japanese Yen',
    name: 'sJPY',
  },
  {
    feed: '0x0',
    asset: 'AUD',
    category: 'forex',
    sign: '$',
    description: 'Australian Dollars',
    name: 'sAUD',
  },
  {
    feed: '0x0',
    asset: 'GBP',
    category: 'forex',
    sign: '£',
    description: 'Pound Sterling',
    name: 'sGBP',
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'CHF',
    category: 'forex',
    sign: 'Fr',
    description: 'Swiss Franc',
    name: 'sCHF',
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'XAU',
    category: 'commodity',
    sign: 'oz',
    description: 'Gold Ounce',
    name: 'sXAU',
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'XAG',
    category: 'commodity',
    sign: 'oz',
    description: 'Silver Ounce',
    name: 'sXAG',
  },
  {
    feed: '0x0',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Bitcoin',
    name: 'sBTC',
  },
  {
    feed: '0x0',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Ether',
    name: 'sETH',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x0',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    description: 'Binance Coin',
    name: 'sBNB',
  },
  {
    feed: '0x0',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    description: 'TRON',
    name: 'sTRX',
  },
  {
    feed: '0x0',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    description: 'Tezos',
    name: 'sXTZ',
  },
  {
    feed: '0x0',
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    description: 'Ripple',
    name: 'sXRP',
  },
  {
    feed: '0x0',
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    description: 'Litecoin',
    name: 'sLTC',
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    description: 'Chainlink',
    name: 'sLINK',
  },
  {
    feed: '0x0',
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    description: 'EOS',
    name: 'sEOS',
  },
  {
    feed: '0x0',
    asset: 'BCH',
    category: 'crypto',
    sign: '',
    description: 'Bitcoin Cash',
    name: 'sBCH',
  },
  {
    feed: '0x0',
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    description: 'Ethereum Classic',
    name: 'sETC',
  },
  {
    feed: '0x0',
    asset: 'DASH',
    category: 'crypto',
    sign: '',
    description: 'Dash',
    name: 'sDASH',
  },
  {
    feed: '0x0',
    asset: 'XMR',
    category: 'crypto',
    sign: '',
    description: 'Monero',
    name: 'sXMR',
  },
  {
    feed: '0x0',
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    description: 'Cardano',
    name: 'sADA',
  },
  {
    feed: '0x0',
    asset: 'CEX',
    category: 'index',
    sign: '',
    description: 'Centralised Exchange Index',
    name: 'sCEX',
    index: [
      {
        asset: 'BNB',
        category: 'crypto',
        sign: '',
        description: 'Binance Coin',
        units: 12.88,
        weight: 29.15,
      },
      {
        asset: 'CRO',
        category: 'crypto',
        sign: '',
        description: 'Crypto com',
        units: 1303.31,
        weight: 24.3,
      },
      {
        asset: 'LEO',
        category: 'crypto',
        sign: '',
        description: 'UNUS SED LEO',
        units: 94.54,
        weight: 13.42,
      },
      {
        asset: 'HT',
        category: 'crypto',
        sign: '',
        description: 'Huobi Token',
        units: 23.06,
        weight: 11.73,
      },
      {
        asset: 'FTT',
        category: 'crypto',
        sign: '',
        description: 'FTX',
        units: 9.36,
        weight: 3.56,
      },
      {
        asset: 'OKB',
        category: 'crypto',
        sign: '',
        description: 'OKB',
        units: 25.72,
        weight: 16.97,
      },
      {
        asset: 'KCS',
        category: 'crypto',
        sign: '',
        description: 'KuCoin Shares',
        units: 9.18,
        weight: 0.87,
      },
    ],
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'DEFI',
    category: 'index',
    sign: '',
    description: 'DeFi Index',
    name: 'sDEFI',
    index: [
      {
        asset: 'COMP',
        category: 'crypto',
        sign: '',
        description: 'Compound',
        units: 4.14,
        weight: 20.5,
      },
      {
        asset: 'MKR',
        category: 'crypto',
        sign: '',
        description: 'Maker',
        units: 0.74,
        weight: 15,
      },
      {
        asset: 'ZRX',
        category: 'crypto',
        sign: '',
        description: '0x',
        units: 668.16,
        weight: 9.7,
      },
      {
        asset: 'REP',
        category: 'crypto',
        sign: '',
        description: 'Augur',
        units: 9.52,
        weight: 7.2,
      },
      { asset: 'LEND', units: 581.76, weight: 6.7 },
      {
        asset: 'UMA',
        category: 'crypto',
        sign: '',
        description: 'UMA',
        units: 28.54,
        weight: 4.2,
      },
      {
        asset: 'SNX',
        category: 'crypto',
        sign: '',
        description: 'Synthetix Network Token',
        units: 82.84,
        weight: 10.2,
      },
      {
        asset: 'REN',
        category: 'crypto',
        sign: '',
        description: 'Ren',
        units: 822.92,
        weight: 5,
      },
      {
        asset: 'LRC',
        category: 'crypto',
        sign: '',
        description: 'Loopring',
        units: 948.31,
        weight: 3.8,
      },
      {
        asset: 'KNC',
        category: 'crypto',
        sign: '',
        description: 'Kyber Network',
        units: 224.53,
        weight: 11.8,
      },
      {
        asset: 'BNT',
        category: 'crypto',
        sign: '',
        description: 'Bancor',
        units: 61.2,
        weight: 3.4,
      },
      {
        asset: 'BAL',
        category: 'crypto',
        sign: '',
        description: 'Balancer',
        units: 7.09,
        weight: 2.5,
      },
    ],
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Inverse Bitcoin',
    name: 'iBTC',
    inverted: { entryPoint: 10600, upperLimit: 15900, lowerLimit: 5300 },
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Inverse Ether',
    name: 'iETH',
    inverted: { entryPoint: 180.16, upperLimit: 315.28, lowerLimit: 45.04 },
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    description: 'Inverse Binance Coin',
    name: 'iBNB',
    inverted: { entryPoint: 29, upperLimit: 44, lowerLimit: 14.5 },
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    description: 'Inverse TRON',
    name: 'iTRX',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 0.025, upperLimit: 0.0375, lowerLimit: 0.0125 },
  },
  {
    feed: '0x0',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    description: 'Inverse Tezos',
    name: 'iXTZ',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 1.4, upperLimit: 2.1, lowerLimit: 0.7 },
  },
  {
    feed: '0x0',
    asset: 'CEX',
    category: 'index',
    sign: '',
    description: 'Inverse Centralised Exchange Index',
    name: 'iCEX',
    index: [
      {
        asset: 'BNB',
        category: 'crypto',
        sign: '',
        description: 'Binance Coin',
        units: 12.88,
        weight: 29.15,
      },
      {
        asset: 'CRO',
        category: 'crypto',
        sign: '',
        description: 'Crypto com',
        units: 1303.31,
        weight: 24.3,
      },
      {
        asset: 'LEO',
        category: 'crypto',
        sign: '',
        description: 'UNUS SED LEO',
        units: 94.54,
        weight: 13.42,
      },
      {
        asset: 'HT',
        category: 'crypto',
        sign: '',
        description: 'Huobi Token',
        units: 23.06,
        weight: 11.73,
      },
      {
        asset: 'FTT',
        category: 'crypto',
        sign: '',
        description: 'FTX',
        units: 9.36,
        weight: 3.56,
      },
      {
        asset: 'OKB',
        category: 'crypto',
        sign: '',
        description: 'OKB',
        units: 25.72,
        weight: 16.97,
      },
      {
        asset: 'KCS',
        category: 'crypto',
        sign: '',
        description: 'KuCoin Shares',
        units: 9.18,
        weight: 0.87,
      },
    ],
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 1000, upperLimit: 1500, lowerLimit: 500 },
  },
  {
    feed: '0x0',
    asset: 'DEFI',
    category: 'index',
    sign: '',
    description: 'Inverse DeFi Index',
    name: 'iDEFI',
    index: [
      {
        asset: 'COMP',
        category: 'crypto',
        sign: '',
        description: 'Compound',
        units: 4.14,
        weight: 20.5,
      },
      {
        asset: 'MKR',
        category: 'crypto',
        sign: '',
        description: 'Maker',
        units: 0.74,
        weight: 15,
      },
      {
        asset: 'ZRX',
        category: 'crypto',
        sign: '',
        description: '0x',
        units: 668.16,
        weight: 9.7,
      },
      {
        asset: 'REP',
        category: 'crypto',
        sign: '',
        description: 'Augur',
        units: 9.52,
        weight: 7.2,
      },
      { asset: 'LEND', units: 581.76, weight: 6.7 },
      {
        asset: 'UMA',
        category: 'crypto',
        sign: '',
        description: 'UMA',
        units: 28.54,
        weight: 4.2,
      },
      {
        asset: 'SNX',
        category: 'crypto',
        sign: '',
        description: 'Synthetix Network Token',
        units: 82.84,
        weight: 10.2,
      },
      {
        asset: 'REN',
        category: 'crypto',
        sign: '',
        description: 'Ren',
        units: 822.92,
        weight: 5,
      },
      {
        asset: 'LRC',
        category: 'crypto',
        sign: '',
        description: 'Loopring',
        units: 948.31,
        weight: 3.8,
      },
      {
        asset: 'KNC',
        category: 'crypto',
        sign: '',
        description: 'Kyber Network',
        units: 224.53,
        weight: 11.8,
      },
      {
        asset: 'BNT',
        category: 'crypto',
        sign: '',
        description: 'Bancor',
        units: 61.2,
        weight: 3.4,
      },
      {
        asset: 'BAL',
        category: 'crypto',
        sign: '',
        description: 'Balancer',
        units: 7.09,
        weight: 2.5,
      },
    ],
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 2757, upperLimit: 4135.5, lowerLimit: 1378.5 },
  },
  {
    feed: '0x0',
    asset: 'FTSE100',
    category: 'equities',
    sign: '',
    exchange: 'LSE',
    description: 'FTSE 100 Index',
    name: 'sFTSE',
  },
  {
    feed: '0x0',
    asset: 'NIKKEI225',
    category: 'equities',
    sign: '',
    exchange: 'TSE',
    description: 'Nikkei 225 Index',
    name: 'sNIKKEI',
  },
];

export default {
  56: MAINNET_SYNTHS,
  97: TESTNET_SYNTHS,
};
