const TESTNET_SYNTHS = [
  {
    asset: 'USD',
    category: 'forex',
    sign: '$',
    description: 'US Dollars',
    name: 'hUSD',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x0',
    asset: 'EUR',
    category: 'forex',
    sign: '€',
    description: 'Euros',
    name: 'hEUR',
  },
  {
    feed: '0x0',
    asset: 'JPY',
    category: 'forex',
    sign: '¥',
    description: 'Japanese Yen',
    name: 'hJPY',
  },
  {
    feed: '0x0',
    asset: 'AUD',
    category: 'forex',
    sign: '$',
    description: 'Australian Dollars',
    name: 'hAUD',
  },
  {
    feed: '0x0',
    asset: 'GBP',
    category: 'forex',
    sign: '£',
    description: 'Pound Sterling',
    name: 'hGBP',
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'CHF',
    category: 'forex',
    sign: 'Fr',
    description: 'Swiss Franc',
    name: 'hCHF',
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'XAU',
    category: 'commodity',
    sign: 'oz',
    description: 'Gold Ounce',
    name: 'hXAU',
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'XAG',
    category: 'commodity',
    sign: 'oz',
    description: 'Silver Ounce',
    name: 'hXAG',
  },
  {
    feed: '0x0',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Bitcoin',
    name: 'hBTC',
  },
  {
    feed: '0x0',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Ether',
    name: 'hETH',
  },
  {
    feed: '0x0',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    description: 'Binance Coin',
    name: 'hBNB',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x0',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    description: 'TRON',
    name: 'hTRX',
  },
  {
    feed: '0x0',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    description: 'Tezos',
    name: 'hXTZ',
  },
  {
    feed: '0x0',
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    description: 'Ripple',
    name: 'hXRP',
  },
  {
    feed: '0x0',
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    description: 'Litecoin',
    name: 'hLTC',
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    description: 'Chainlink',
    name: 'hLINK',
  },
  {
    feed: '0x0',
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    description: 'EOS',
    name: 'hEOS',
  },
  {
    feed: '0x0',
    asset: 'BCH',
    category: 'crypto',
    sign: '',
    description: 'Bitcoin Cash',
    name: 'hBCH',
  },
  {
    feed: '0x0',
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    description: 'Ethereum Classic',
    name: 'hETC',
  },
  {
    feed: '0x0',
    asset: 'DASH',
    category: 'crypto',
    sign: '',
    description: 'Dash',
    name: 'hDASH',
  },
  {
    feed: '0x0',
    asset: 'XMR',
    category: 'crypto',
    sign: '',
    description: 'Monero',
    name: 'hXMR',
  },
  {
    feed: '0x0',
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    description: 'Cardano',
    name: 'hADA',
  },
  {
    feed: '0x0',
    asset: 'CEX',
    category: 'index',
    sign: '',
    description: 'Centralised Exchange Index',
    name: 'hCEX',
    index: [
      {
        asset: 'BNB',
        category: 'crypto',
        sign: '',
        description: 'Binance Coin',
        units: 12.88,
        weight: 29.15,
      },
      {
        asset: 'CRO',
        category: 'crypto',
        sign: '',
        description: 'Crypto com',
        units: 1303.31,
        weight: 24.3,
      },
      {
        asset: 'LEO',
        category: 'crypto',
        sign: '',
        description: 'UNUS SED LEO',
        units: 94.54,
        weight: 13.42,
      },
      {
        asset: 'HT',
        category: 'crypto',
        sign: '',
        description: 'Huobi Token',
        units: 23.06,
        weight: 11.73,
      },
      {
        asset: 'FTT',
        category: 'crypto',
        sign: '',
        description: 'FTX',
        units: 9.36,
        weight: 3.56,
      },
      {
        asset: 'OKB',
        category: 'crypto',
        sign: '',
        description: 'OKB',
        units: 25.72,
        weight: 16.97,
      },
      {
        asset: 'KCS',
        category: 'crypto',
        sign: '',
        description: 'KuCoin Shares',
        units: 9.18,
        weight: 0.87,
      },
    ],
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'DEFI',
    category: 'index',
    sign: '',
    description: 'DeFi Index',
    name: 'hDEFI',
    index: [
      {
        asset: 'COMP',
        category: 'crypto',
        sign: '',
        description: 'Compound',
        units: 4.14,
        weight: 20.5,
      },
      {
        asset: 'MKR',
        category: 'crypto',
        sign: '',
        description: 'Maker',
        units: 0.74,
        weight: 15,
      },
      {
        asset: 'ZRX',
        category: 'crypto',
        sign: '',
        description: '0x',
        units: 668.16,
        weight: 9.7,
      },
      {
        asset: 'REP',
        category: 'crypto',
        sign: '',
        description: 'Augur',
        units: 9.52,
        weight: 7.2,
      },
      { asset: 'LEND', units: 581.76, weight: 6.7 },
      {
        asset: 'UMA',
        category: 'crypto',
        sign: '',
        description: 'UMA',
        units: 28.54,
        weight: 4.2,
      },
      {
        asset: 'SNX',
        category: 'crypto',
        sign: '',
        description: 'Synthetix Network Token',
        units: 82.84,
        weight: 10.2,
      },
      {
        asset: 'REN',
        category: 'crypto',
        sign: '',
        description: 'Ren',
        units: 822.92,
        weight: 5,
      },
      {
        asset: 'LRC',
        category: 'crypto',
        sign: '',
        description: 'Loopring',
        units: 948.31,
        weight: 3.8,
      },
      {
        asset: 'KNC',
        category: 'crypto',
        sign: '',
        description: 'Kyber Network',
        units: 224.53,
        weight: 11.8,
      },
      {
        asset: 'BNT',
        category: 'crypto',
        sign: '',
        description: 'Bancor',
        units: 61.2,
        weight: 3.4,
      },
      {
        asset: 'BAL',
        category: 'crypto',
        sign: '',
        description: 'Balancer',
        units: 7.09,
        weight: 2.5,
      },
    ],
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Inverse Bitcoin',
    name: 'iBTC',
    inverted: { entryPoint: 10600, upperLimit: 15900, lowerLimit: 5300 },
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Inverse Ether',
    name: 'iETH',
    inverted: { entryPoint: 180.16, upperLimit: 315.28, lowerLimit: 45.04 },
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    description: 'Inverse Binance Coin',
    name: 'iBNB',
    inverted: { entryPoint: 29, upperLimit: 44, lowerLimit: 14.5 },
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    description: 'Inverse TRON',
    name: 'iTRX',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 0.025, upperLimit: 0.0375, lowerLimit: 0.0125 },
  },
  {
    feed: '0x0',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    description: 'Inverse Tezos',
    name: 'iXTZ',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 1.4, upperLimit: 2.1, lowerLimit: 0.7 },
  },
  {
    feed: '0x0',
    asset: 'CEX',
    category: 'index',
    sign: '',
    description: 'Inverse Centralised Exchange Index',
    name: 'iCEX',
    index: [
      {
        asset: 'BNB',
        category: 'crypto',
        sign: '',
        description: 'Binance Coin',
        units: 12.88,
        weight: 29.15,
      },
      {
        asset: 'CRO',
        category: 'crypto',
        sign: '',
        description: 'Crypto com',
        units: 1303.31,
        weight: 24.3,
      },
      {
        asset: 'LEO',
        category: 'crypto',
        sign: '',
        description: 'UNUS SED LEO',
        units: 94.54,
        weight: 13.42,
      },
      {
        asset: 'HT',
        category: 'crypto',
        sign: '',
        description: 'Huobi Token',
        units: 23.06,
        weight: 11.73,
      },
      {
        asset: 'FTT',
        category: 'crypto',
        sign: '',
        description: 'FTX',
        units: 9.36,
        weight: 3.56,
      },
      {
        asset: 'OKB',
        category: 'crypto',
        sign: '',
        description: 'OKB',
        units: 25.72,
        weight: 16.97,
      },
      {
        asset: 'KCS',
        category: 'crypto',
        sign: '',
        description: 'KuCoin Shares',
        units: 9.18,
        weight: 0.87,
      },
    ],
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 1000, upperLimit: 1500, lowerLimit: 500 },
  },
  {
    feed: '0x0',
    asset: 'DEFI',
    category: 'index',
    sign: '',
    description: 'Inverse DeFi Index',
    name: 'iDEFI',
    index: [
      {
        asset: 'COMP',
        category: 'crypto',
        sign: '',
        description: 'Compound',
        units: 4.14,
        weight: 20.5,
      },
      {
        asset: 'MKR',
        category: 'crypto',
        sign: '',
        description: 'Maker',
        units: 0.74,
        weight: 15,
      },
      {
        asset: 'ZRX',
        category: 'crypto',
        sign: '',
        description: '0x',
        units: 668.16,
        weight: 9.7,
      },
      {
        asset: 'REP',
        category: 'crypto',
        sign: '',
        description: 'Augur',
        units: 9.52,
        weight: 7.2,
      },
      { asset: 'LEND', units: 581.76, weight: 6.7 },
      {
        asset: 'UMA',
        category: 'crypto',
        sign: '',
        description: 'UMA',
        units: 28.54,
        weight: 4.2,
      },
      {
        asset: 'SNX',
        category: 'crypto',
        sign: '',
        description: 'Synthetix Network Token',
        units: 82.84,
        weight: 10.2,
      },
      {
        asset: 'REN',
        category: 'crypto',
        sign: '',
        description: 'Ren',
        units: 822.92,
        weight: 5,
      },
      {
        asset: 'LRC',
        category: 'crypto',
        sign: '',
        description: 'Loopring',
        units: 948.31,
        weight: 3.8,
      },
      {
        asset: 'KNC',
        category: 'crypto',
        sign: '',
        description: 'Kyber Network',
        units: 224.53,
        weight: 11.8,
      },
      {
        asset: 'BNT',
        category: 'crypto',
        sign: '',
        description: 'Bancor',
        units: 61.2,
        weight: 3.4,
      },
      {
        asset: 'BAL',
        category: 'crypto',
        sign: '',
        description: 'Balancer',
        units: 7.09,
        weight: 2.5,
      },
    ],
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 2757, upperLimit: 4135.5, lowerLimit: 1378.5 },
  },
  {
    feed: '0x0',
    asset: 'FTSE100',
    category: 'equities',
    sign: '',
    exchange: 'LSE',
    description: 'FTSE 100 Index',
    name: 'hFTSE',
  },
  {
    feed: '0x0',
    asset: 'NIKKEI225',
    category: 'equities',
    sign: '',
    exchange: 'TSE',
    description: 'Nikkei 225 Index',
    name: 'hNIKKEI',
  },
];

export default {
  97: TESTNET_SYNTHS,
};
