const TESTNET_SYNTHS = [
  {
    asset: 'USD',
    category: 'forex',
    sign: '$',
    description: 'US Dollars',
    name: 'hUSD',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x0',
    asset: 'EUR',
    category: 'forex',
    sign: '€',
    description: 'Euros',
    name: 'hEUR',
  },
  {
    feed: '0x0',
    asset: 'JPY',
    category: 'forex',
    sign: '¥',
    description: 'Japanese Yen',
    name: 'hJPY',
  },
  {
    feed: '0x0',
    asset: 'AUD',
    category: 'forex',
    sign: '$',
    description: 'Australian Dollars',
    name: 'hAUD',
  },
  {
    feed: '0x0',
    asset: 'GBP',
    category: 'forex',
    sign: '£',
    description: 'Pound Sterling',
    name: 'hGBP',
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'CHF',
    category: 'forex',
    sign: 'Fr',
    description: 'Swiss Franc',
    name: 'hCHF',
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'XAU',
    category: 'commodity',
    sign: 'oz',
    description: 'Gold Ounce',
    name: 'hXAU',
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'XAG',
    category: 'commodity',
    sign: 'oz',
    description: 'Silver Ounce',
    name: 'hXAG',
  },
  {
    feed: '0x0',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Bitcoin',
    name: 'hBTC',
  },
  {
    feed: '0x0',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Ether',
    name: 'hETH',
  },
  {
    feed: '0x0',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    description: 'Binance Coin',
    name: 'hBNB',
    subclass: 'MultiCollateralSynth',
  },
  {
    feed: '0x0',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    description: 'TRON',
    name: 'hTRX',
  },
  {
    feed: '0x0',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    description: 'Tezos',
    name: 'hXTZ',
  },
  {
    feed: '0x0',
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    description: 'Ripple',
    name: 'hXRP',
  },
  {
    feed: '0x0',
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    description: 'Litecoin',
    name: 'hLTC',
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    description: 'Chainlink',
    name: 'hLINK',
  },
  {
    feed: '0x0',
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    description: 'EOS',
    name: 'hEOS',
  },
  {
    feed: '0x0',
    asset: 'BCH',
    category: 'crypto',
    sign: '',
    description: 'Bitcoin Cash',
    name: 'hBCH',
  },
  {
    feed: '0x0',
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    description: 'Ethereum Classic',
    name: 'hETC',
  },
  {
    feed: '0x0',
    asset: 'DASH',
    category: 'crypto',
    sign: '',
    description: 'Dash',
    name: 'hDASH',
  },
  {
    feed: '0x0',
    asset: 'XMR',
    category: 'crypto',
    sign: '',
    description: 'Monero',
    name: 'hXMR',
  },
  {
    feed: '0x0',
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    description: 'Cardano',
    name: 'hADA',
  },
  {
    feed: '0x0',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Inverse Inverse Inverse Bitcoin',
    name: 'iBTC',
    inverted: { entryPoint: 10600, upperLimit: 15900, lowerLimit: 5300 },
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Inverse Inverse Inverse Ether',
    name: 'iETH',
    inverted: { entryPoint: 180.16, upperLimit: 315.28, lowerLimit: 45.04 },
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    description: 'Inverse Inverse Inverse Binance Coin',
    name: 'iBNB',
    inverted: { entryPoint: 29, upperLimit: 44, lowerLimit: 14.5 },
    subclass: 'PurgeableSynth',
  },
  {
    feed: '0x0',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    description: 'Inverse Inverse Inverse TRON',
    name: 'iTRX',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 0.025, upperLimit: 0.0375, lowerLimit: 0.0125 },
  },
  {
    feed: '0x0',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    description: 'Inverse Inverse Inverse Tezos',
    name: 'iXTZ',
    subclass: 'PurgeableSynth',
    inverted: { entryPoint: 1.4, upperLimit: 2.1, lowerLimit: 0.7 },
  },
];

export default {
  97: TESTNET_SYNTHS,
};
